#!/bin/sh

##### chromium-browser #####
sudo add-apt-repository ppa:chromium-daily/ppa
##### jdownloader #####
sudo add-apt-repository ppa:jd-team/jdownloader
##### ubuntu tweak #####
sudo add-apt-repository ppa:tualatrix/ppa
##### faenza-icons #####
sudo add-apt-repository ppa:tiheum/equinox
##### sys indicator #####
sudo add-apt-repository ppa:alexeftimie/ppa
