#!/bin/sh

# chromium
gconftool-2 --type string --set /desktop/gnome/applications/browser/exec '/usr/bin/chromium-browser'

# instant shutdown
gconftool-2 --type bool --set /apps/indicator-session/suppress_logout_restart_shutdown true 

# nautilus
gconftool-2 --type string --set /apps/nautilus/preferences/default_folder_viewer list_view
gconftool-2 --type string --set /apps/nautilus/list_view/default_zoom_level smallest 
gconftool-2 --type string --set /apps/nautilus/preferences/show_directory_item_counts always 
gconftool-2 --type string --set /apps/nautilus/preferences/click_policy 'single'
gconftool-2 --type bool --set /apps/nautilus/preferences/media_automount_open false
gconftool-2 --type bool --set /apps/nautilus/preferences/media_autorun_never true
gconftool-2 --type bool --set /apps/nautilus/preferences/enable_delete true
gconftool-2 --type bool --set /apps/nautilus/preferences/media_automount_open false
gconftool-2 --type bool --set /apps/nautilus/preferences/media_autorun_never true
gconftool-2 --type bool --set /apps/nautilus/preferences/enable_delete true

# eog
gconftool-2 --type list --list-type string --set /apps/eog/plugins/active_plugins [fullscreen,statusbar-date]
gconftool-2 --type bool --set /apps/eog/ui/disable_trash_confirmation true 

# disable screensaver lock
gconftool-2 --type bool --set /apps/gnome-screensaver/lock_enabled false

# gnome-terminal
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/use_theme_colors false
gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/background_color '#FFFFFFFFFFFF'
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/use_theme_background false
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/scrollback_unlimited true

# gedit
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/current_line/highlight_current_line true
gconftool-2 --type string --set /apps/gedit-2/preferences/editor/colors/scheme 'oblivion'
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/bracket_matching/bracket_matching true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/auto_indent/auto_indent true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/line_numbers/display_line_numbers true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/right_margin/display_right_margin true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/save/create_backup_copy true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/save/auto_save true
gconftool-2 --type int --set /apps/gedit-2/preferences/editor/tabs/tabs_size 4
gconftool-2 --type bool --set /apps/gedit-2/preferences/ui/side_pane/side_pane_visible true
gconftool-2 --type list --list-type string --set /apps/gedit-2/plugins/active-plugins [tabswitch,modelines,docinfo,filebrowser,sessionsaver,codecomment]



