#!/bin/sh

# unity
gconftool-2 --type int --set /apps/compiz-1/plugins/unityshell/screen0/options/launcher_hide_mode 1

#shortcuts
# gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_12 '<Control><Alt>adiaeresis'
# gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_12 '~/Projekte/Skripte/SynergyClient.sh'

# energy management
# on/off
gconftool-2 --type string --set /apps/gnome-power-manager/buttons/power 'interactive'
# AC
gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_computer_ac 0
gconftool-2 --type string --set /apps/gnome-power-manager/buttons/lid_ac 'blank'
gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_display_ac 0

# battery
gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_computer_battery 0
gconftool-2 --type string --set /apps/gnome-power-manager/buttons/lid_battery 'blank'
gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_display_battery 60
gconftool-2 --type string --set /apps/gnome-power-manager/actions/critical_battery 'hibernate'
gconftool-2 --type bool --set /apps/gnome-power-manager/backlight/idle_dim_battery true
gconftool-2 --type bool --set /apps/gnome-power-manager/backlight/battery_reduce true
gconftool-2 --type bool --set /apps/gnome-power-manager/disks/spindown_enable_battery true
