#!/bin/sh

# no volumes on desktop
gconftool-2 --type bool --set /apps/nautilus/desktop/volumes_visible false  

# dock doesn't hide
gconftool-2 --type float --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/FadeOpacity 0.6  

# remove Docky icon
gconftool-2 --type Boolean --set /apps/docky-2/Docky/Items/DockyItem/ShowDockyItem False

# icons in menu
gconftool-2 --type bool --set /desktop/gnome/interface/menus_have_icons true 

# instant shutdown
gconftool-2 --type bool --set /apps/indicator-session/suppress_logout_restart_shutdown true 

# nautilus
gconftool-2 --type string --set /apps/nautilus/preferences/default_folder_viewer list_view
gconftool-2 --type string --set /apps/nautilus/list_view/default_zoom_level smallest
gconftool-2 --type string --set /apps/nautilus/preferences/show_directory_item_counts always 
gconftool-2 --type string --set /apps/nautilus/preferences/click_policy 'single'

# eog - delete without prompt
gconftool-2 --type bool --set /apps/eog/ui/disable_trash_confirmation true 

# roll in window on scroll over titlebar
gconftool-2 --type string --set /apps/metacity/general/action_middle_click_titlebar minimize
gconftool-2 --type string --set /apps/gwd/mouse_wheel_action shade 

# clock
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/custom_format '<sup><span rise="300" font_desc="Sans 6.7" weight="normal">%a %d %b</span></sup>%n<sub><span font_desc="Sans 7.5" weight="bold">%H:%M:%S</span></sub>'
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/format custom 
gconftool-2 --type bool --set /apps/panel/applets/clock_screen0/prefs/show_seconds true

# disable screensaver
gconftool-2 --type bool --set /apps/gnome-screensaver/idle_activation_enabled false

# weather settings
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/cities '[<location name="Chemnitz" city="" timezone="Europe/Berlin" latitude="50.000000" longitude="12.000000" code="EDAC" current="true"/>]'

# disable autoopen and autorun
gconftool-2 --type bool --set /apps/nautilus/preferences/media_automount_open false
gconftool-2 --type bool --set /apps/nautilus/preferences/media_autorun_never true

# enable delete
gconftool-2 --type bool --set /apps/nautilus/preferences/enable_delete true

# enable menu-button
gconftool-2 --type string --set /apps/metacity/general/button_layout 'close,minimize,maximize:menu'

####################
#### shortcuts #####
####################

# Windows + T => gnome-terminal
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_1 '<Super>t'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_1 gnome-terminal 

# avoid conflicts
gconftool-2 --type string --set /apps/compiz/plugins/expo/allscreens/options/expo_key '<Super>q'

# Windows + E => Nautilus
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_2 '<Super>e'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_2 nautilus

# laptop only: STRG + Ä => synergy 
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_3 '<Super>adiaeresis'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_3 '~/Projekte/Skripte/SynergyClient.sh'

# Windows + R => Gedit
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_4 '<Super>r'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_4 gedit

# STRG + ALT + + => next song
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/next '<Control><Alt>plus'
# STRG + ALT + - => previous song
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/previous '<Control><Alt>minus'
# STRG + ALT + # => play/pause
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/play '<Control><Alt>numbersign' 


####################
##### compiz #######
####################

gconftool-2 --type string --set /apps/compiz/plugins/decoration/allscreens/options/shadow_match '!title=my_conky'

####################
#### terminal ######
####################

# unlimited scrolling
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/scrollback_unlimited true

# window size
gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/default_size_columns '118'
gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/default_size_rows '32'

# theme
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/use_theme_colors false

# disable menubar
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/default_show_menubar false


####################
##### gedit ########
####################

gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/current_line/highlight_current_line true
gconftool-2 --type string --set /apps/gedit-2/preferences/editor/colors/scheme 'oblivion'
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/bracket_matching/bracket_matching true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/auto_indent/auto_indent true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/line_numbers/display_line_numbers true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/right_margin/display_right_margin true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/save/create_backup_copy true
gconftool-2 --type bool --set /apps/gedit-2/preferences/editor/save/auto_save true
gconftool-2 --type int --set /apps/gedit-2/preferences/editor/tabs/tabs_size 4
gconftool-2 --type bool --set /apps/gedit-2/preferences/ui/side_pane/side_pane_visible true
gconftool-2 --type list --list-type string --set /apps/gedit-2/plugins/active-plugins [tabswitch,GeditLaTeXPlugin,docinfo,filebrowser,sessionsaver,codecomment]
