#!/bin/sh

# no volumes on desktop
gconftool-2 --type bool --set /apps/nautilus/desktop/volumes_visible false  

# dock doesn't hide
gconftool-2 --type float --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/FadeOpacity 0.6  

# icons in menu
gconftool-2 --type bool --set /desktop/gnome/interface/menus_have_icons true 

# instant shutdown
gconftool-2 --type bool --set /apps/indicator-session/suppress_logout_restart_shutdown true 

# nautilus
gconftool-2 --type string --set /apps/nautilus/preferences/default_folder_viewer list_view
gconftool-2 --type string --set /apps/nautilus/list_view/default_zoom_level smallest
gconftool-2 --type string --set /apps/nautilus/preferences/show_directory_item_counts always 

# eog - delete without prompt
gconftool-2 --type bool --set /apps/eog/ui/disable_trash_confirmation true 

# roll in window on scroll over titlebar
gconftool-2 --type string --set /apps/metacity/general/action_middle_click_titlebar minimize
gconftool-2 --type string --set /apps/gwd/mouse_wheel_action shade 

# clock
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/custom_format '<sup><span rise="3000" font_desc="Sans 7.5" color="#F0EBE2" weight="normal">%a %d %b</span></sup>%n<sub><span font_desc="Sans 7.5" color="#F0EBE2" weight="bold">%H:%M:%S</span></sub>'
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/format custom 

# disable screensaver
gconftool-2 --type bool --set /apps/gnome-screensaver/idle_activation_enabled false

# weather settings
gconftool-2 --type string --set /apps/panel/applets/clock_screen0/prefs/cities '[<location name="Chemnitz" city="" timezone="Europe/Berlin" latitude="50.000000" longitude="12.000000" code="EDAC" current="true"/>]'

# disable autoopen and autorun
gconftool-2 --type bool --set /apps/nautilus/preferences/media_automount_open false
gconftool-2 --type bool --set /apps/nautilus/preferences/media_autorun_never true

####################
#### shortcuts #####
####################

# Windows + T => gnome-terminal
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_1 '<Super>t'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_1 gnome-terminal 

#Komplikationen lösen
gconftool-2 --type string --set /apps/compiz/plugins/expo/allscreens/options/expo_key '<Super>q'

# Windows + E => Nautilus
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_2 '<Super>e'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_2 nautilus

# laptop only: STRG + Ä => synergy 
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_3 '<Super>adiaeresis'
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_3 '~/Projekte/Skripte/SynergyClient.sh'

# STRG + ALT + + => next song
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/next '<Control><Alt>plus'
# STRG + ALT + - => previous song
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/previous '<Control><Alt>minus'
# STRG + ALT + # => play/pause
#gconftool-2 --type string --set /apps/gnome_settings_daemon/keybindings/play '<Control><Alt>numbersign' 


####################
##### compiz #######
####################

gconftool-2 --type string --set /apps/compiz/plugins/decoration/allscreens/options/shadow_match '!title=my_conky'

####################
#### terminal ######
####################
# unlimited scrolling
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/scrollback_unlimited true
# window size
gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/default_size_columns '118'
gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/default_size_rows '32'
# theme
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/use_theme_colors false
# disable menubar
gconftool-2 --type bool --set /apps/gnome-terminal/profiles/Default/default_show_menubar false


