#!/bin/sh

echo "PS1='\u@\h \[\033[1;34m\]\w\[\033[0m\]\\$ '" >> ~/.bashrc

cp ./configs/.xbindkeysrc ~/
cp ./configs/.hidden ~/
cp ./configs/.gitconfig ~/
cp -R ./configs/.gnome2 ~/
cp -R ./configs/.icons ~/
sudo gtk-update-icon-cache

sudo cp -R ./Burg/Minimal /boot/burg/themes/
sudo cp -R ./Burg/MinimalText /boot/burg/themes/

sudo update-burg

chmod 700 ~/.ssh/id_rsa

sudo rm -R /usr/share/pixmaps/pidgin/try/hicolor/*
sudo cp -R ./config/pidgin-tray-icons/* /usr/share/pixmaps/pidgin/tray/hicolor/
