#!/bin/sh

# trust cacert
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n cacert -i /etc/ssl/certs/cacert.org.pem

echo "PS1='\u@\h \[\033[1;34m\]\w\[\033[0m\]\\$ '" >> ~/.bashrc

cp ./dot-files/hidden ~/.hidden
cp -R ./dot-files/icons ~/.icons
cp -R ./dot-files/gnome2 ~/.gnome2
mkdir -p ~/.purple/logs

sudo gtk-update-icon-cache

chmod 700 ~/.ssh/id_dsa

rm ~/examples.desktop

# black plymouth
sed -e 's/Window\.SetBackgroundTopColor *(.*)/Window.SetBackgroundTopColor (0.00, 0.00, 0.00)/g' /lib/plymouth/themes/ubuntu-logo/ubuntu-logo.script > HoTh9the1a
sed -e 's/Window\.SetBackgroundBottomColor *(.*)/Window.SetBackgroundBottomColor (0.00, 0.00, 0.00)/g' HoTh9the1a > uPh7Chuoqu
sudo mv uPh7Chuoqu /lib/plymouth/themes/ubuntu-logo/ubuntu-logo.script
rm HoTh9the1a
