#!/bin/sh

# files
ln -fs -T Projekte/UbuntuPersonalizer/dot-files-fixed/xbindkeysrc /home/kabum/.xbindkeysrc
ln -fs -T Projekte/UbuntuPersonalizer/dot-files-fixed/gitconfig /home/kabum/.gitconfig
ln -fs -T ../Projekte/UbuntuPersonalizer/dot-files-fixed/sshconfig /home/kabum/.ssh/config
ln -fs -T Projekte/UbuntuPersonalizer/dot-files-fixed/vimrc /home/kabum/.vimrc
# dirs
ln -fs -t /home/kabum Projekte/UbuntuPersonalizer/dot-files-fixed/.vim
