#!/bin/sh

# lighttpd conf
mkdir -p /home/kabum/Projekte/www/Archiv
sudo lighty-enable-mod userdir
sudo lighty-enable-mod fastcgi-php
echo 'server.bind = "127.0.0.1"' | sudo tee -a /etc/lighttpd/lighttpd.conf
sudo service lighttpd reload
