#!/bin/sh

ln -s Projekte/UbuntuPersonalizer/dot-files-fixed/xbindkeysrc /home/kabum/.xbindkeysrc
ln -s Projekte/UbuntuPersonalizer/dot-files-fixed/gitconfig /home/kabum/.gitconfig
ln -s ../Projekte/UbuntuPersonalizer/dot-files-fixed/sshconfig /home/kabum/.ssh/config
