#!/bin/sh

####################
### adding ppa's ###
####################

##### chromium-browser #####
sudo add-apt-repository ppa:chromium-daily/ppa
##### elementary-theme elementary-icon-theme #####
sudo add-apt-repository ppa:elementaryart/ppa
##### panflute-applet #####
sudo add-apt-repository ppa:kuliniew/ppa
##### pinta ####
sudo add-apt-repository ppa:moonlight-team/pinta
##### shotwell #####
sudo add-apt-repository ppa:yorba/ppa
##### ubuntu tweak #####
sudo add-apt-repository ppa:tualatrix/ppa
##### elementary-nautilus #####
sudo add-apt-repository ppa:am-monkeyd/nautilus-elementary-ppa
##### burg boot loader #####
sudo add-apt-repository ppa:bean123ch/burg
##### docky #####
sudo add-apt-repository ppa:docky-core/ppa

sudo apt-get update
sudo apt-get -y upgrade

nautilus -q

####################
#### installing ####
####################

sudo apt-get -y install apache2 banshee banshee-extension-alarm banshee-extension-lyric burg burg-themes chromium-browser chromium-browser-l10n compiz-fusion-plugins-extra compizconfig-settings-manager conky deja-dup desktop-webmail discus docky elementary-icon-theme elementary-theme gconf-editor gedit-latex-plugin gedit-plugins git-core gparted hardware-monitor htop latex-beamer linuxdcp meld nmap ntfsprogs openjdk-6-jre openssh-server pan panflute-applet pdfshuffler php5 picard pidgin pinta pwgen pyrenamer pyroom sgt-puzzles shotwell simple-ccsm skype synergy tasque texlive-full tree ubuntu-restricted-extras ubuntu-tweak unison unison-gtk vim virtualbox-ose virtualbox-ose-guest-utils vlc xautomation xbindkeys xournals

sudo apt-get -y remove empathy ekiga

sudo burg-install "(hd0)"
sudo update-burg
