#!/bin/sh

##### elementary-theme elementary-icon-theme #####
#sudo add-apt-repository ppa:elementaryart/ppa
##### elementary-nautilus #####
sudo add-apt-repository ppa:am-monkeyd/nautilus-elementary-ppa
##### osd-lyrics #####
sudo add-apt-repository ppa:osd-lyrics/ppa
##### faenza-icon-theme #####
sudo add-apt-repository ppa:tiheum/equinox

sudo apt-get -y install nautilus

nautilus -q

sudo apt-get -y install burg burg-themes chromium-browser-l10n chromium-codecs-ffmpeg compiz-fusion-plugins-extra faenza-icon-theme gparted   openjdk-6-jre osdlyrics pyroom simple-ccsm tasque 

