#!/bin/sh

####################
### adding ppa's ###
####################

##### chromium-browser #####
sudo add-apt-repository ppa:chromium-daily/beta
##### elementary-theme elementary-icon-theme #####
sudo add-apt-repository ppa:elementaryart/ppa
##### panflute-applet #####
sudo add-apt-repository ppa:kuliniew/ppa
##### pinta ####
sudo add-apt-repository ppa:moonlight-team/pinta
##### shotwell #####
sudo add-apt-repository ppa:yorba/ppa
##### ubuntu tweak #####
sudo add-apt-repository ppa:tualatrix/ppa

####################
#### installing ####
####################

sudo apt-get install apache2 chromium-browser chromium-browser-l10n compiz-fusion-plugins-extra compizconfig-settings-manager conky discus docky gconf-editor gedit-plugins git-core gparted hardware-monitor htop latex-beamer mdadm nmap ntfsprogs openjdk-6-jre openssh-server panflute-applet pdfshuffler php5 picard pidgin pinta pwgen pyrenamer python-gdm2setup sgt-puzzles shotwell simple-ccsm synergy tasque texlive-full texmaker tree ubuntu-restricted-extras unison unison-gtk vim virtualbox-ose virtualbox-ose-guest-utils vlc xautomation xbindkeys 

sudo apt-get install backintime-gnome desktop-webmail meld ubuntu-tweak

# sudo apt-get install chromium-codecs-ffmpeg-nonfree elementary-icon-theme elementary-theme 
