set number
syntax on
set enc=utf-8
colorscheme wombat256mod
set tabstop=4
set softtabstop=4
set statusline=%F%m%r%h%w\ \|\ %{&ff}\ \|\ %Y\ %=\[%l\/%L\|%v\]%3p%%
set t_Co=256
set laststatus=2
set shiftwidth=4
set mouse=a
set smartindent
set autoindent
set foldmethod=syntax
